#!/bin/bash

M_MACHINE=dlp
QEMU_MACHINE=qemuarm64
MODULAR_TOOLS_DIR=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
DLP_ROOT=$(cd "$MODULAR_TOOLS_DIR/../.." && pwd)

#**************commands section**********************************************
#install prerequisites
setup()
{

 sudo chmod +x downloads/post_sync_hook.sh
 source downloads/post_sync_hook.sh
 sudo apt-get install -y gawk wget git diffstat unzip texinfo gcc-multilib \
 build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
 xz-utils debianutils iputils-ping libsdl1.2-dev xterm libyaml-dev libssl-dev

 sudo apt-get -y install autoconf libtool libglib2.0-dev libarchive-dev \
 sed cvs subversion coreutils texi2html docbook-utils python-pysqlite2 \
 help2man make gcc g++ desktop-file-utils libgl1-mesa-dev libglu1-mesa-dev \
 mercurial automake groff curl lzop asciidoc u-boot-tools dos2unix mtd-utils pv \
 libncurses5 libncurses5-dev libncursesw5-dev libelf-dev zlib1g-dev bc rename git-lfs libsdl2-dev

 sudo apt-get install -y  python3-git

 sudo apt install -y bmap-tools

 sudo apt-get install -y bison g++-multilib git gperf libxml2-utils make python-networkx zip

 sudo apt-get install -y flex curl libncurses5-dev libssl-dev zlib1g-dev gawk minicom

 sudo apt-get install -y exfat-fuse exfat-utils device-tree-compiler liblz4-tool mtools xxhash zstd

 sudo apt-get install -y qemu-system

 sudo apt-get install openssh-client

 mkdir ~/bin
 curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
 chmod a+x ~/bin/repo
 export PATH=~/bin:$PATH
}

#define machine type
machine_type()
{
        export MACHINE=$M_MACHINE
	DISTRO=imx-dlp MACHINE=${MACHINE} source "$DLP_ROOT/dlp-setup-release.sh"
	fix_path
}

#define qemu type
qemu_type()
{
        export MACHINE=$QEMU_MACHINE
	DISTRO=imx-dlp MACHINE=${MACHINE} source "$DLP_ROOT/dlp-setup-release.sh"
	fix_path
}

sanity_fix()
{
	file="$DLP_ROOT/sources/poky/meta/conf/sanity.conf"
	kernel_src="$DLP_ROOT/sources/meta-bsp-dlp/recipes-kernel/linux/files"
	kernel_dst="$DLP_ROOT/sources/meta-imx/meta-bsp/recipes-kernel/linux/files"
	line='INHERIT += "sanity"'
	modified_line='#INHERIT += "sanity"'

	if [ ! -f "$file" ]; then
		echo "sanity.conf not found at $file"
	elif grep -q "$line" "$file"; then
		echo "The line '$line' exists in the file."
		if grep -q "$modified_line" "$file"; then
			echo "The line '$modified_line' already exists and is commented out."
		else
			sed -i "s/$line/$modified_line/g" "$file"
			echo "The line '$line' has been modified to '$modified_line'."
		fi
	else
		echo "The line '$line' does not exist in the file."
	fi
	if [ -d "$kernel_src" ]; then
		mkdir -p "$kernel_dst"
		cp "$kernel_src"/* "$kernel_dst"/
	fi
}

sshd_fix()
{
	cp sources/meta-bsp-me9/tools/sshd_config sources/poky/meta/recipes-connectivity/openssh/openssh/sshd_config
}

fix_path()
{

# Define the path to the original bblayers.conf file
if [ -d conf ]; then
    BBLAYERS_CONF_ORG="conf/bblayers.conf.org"
    BBLAYERS_CONF="conf/bblayers.conf"
else
    BBLAYERS_CONF_ORG="$DLP_ROOT/build/conf/bblayers.conf.org"
    BBLAYERS_CONF="$DLP_ROOT/build/conf/bblayers.conf"
fi
# Check if the original bblayers.conf file exists
if [ ! -f "$BBLAYERS_CONF_ORG" ]; then
    echo "Error: bblayers.conf.org not found at $BBLAYERS_CONF_ORG"
    exit 1
fi

# Update the BSPDIR variable using sed
sed -i '/^BSPDIR :=/c\BSPDIR := "${@os.path.abspath(os.path.dirname(d.getVar('\''FILE'\'', True)) + '\''/../..'\'')}"' "$BBLAYERS_CONF_ORG"

sed -i '/^BSPDIR :=/c\BSPDIR := "${@os.path.abspath(os.path.dirname(d.getVar('\''FILE'\'', True)) + '\''/../..'\'')}"' "$BBLAYERS_CONF"
echo "BSPDIR has been updated in bblayers.conf.org"
	
}
add_new_layer() {
	cp sources/meta-bsp-dlp/bblayers.confpre conf/bblayers.conf.org
}

#build image for machine
build_image_evb()
{
	echo " not work now - fix soon"
	#machine_type
	#sanity_fix
	#bitbake -k core-image-base
	#fix_path
}

build_image_pcb()
{
	machine_type
	sanity_fix
	bitbake -k imx-boot core-image-minimal
	#fix_path
}

#build image for QEMU
build_image_qemu()
{
	qemu_type
	sanity_fix
	bitbake -k core-image-minimal
	#fix_path
}

rebuild_image_evb()
{
    bitbake -k core-image-base
}

rebuild_image_pcb()
{
	export PATH=/usr/bin:$PATH
	cd build
    bitbake -k imx-boot core-image-minimal
}

build_sdk()
{
	machine_type
	bitbake core-image-minimal -c populate_sdk
}

flash_to_emmc()
{
	pushd .
	cp sources/meta-bsp-dlp/uuu sources/meta-bsp-dlp/uuu build/tmp/deploy/images/imx8mpevk/
	cd build/tmp/deploy/images/imx8mpevk/
	sudo ./uuu -b emmc_all imx-boot core-image-minimal-imx8mpevk.wic.zst
	popd
}


sync_project()
{
	repo forall -c 'git reset --hard HEAD; git clean -fdx'
	repo sync -j4
}

help()
{
	echo $BASH_SOURCE "<parameter>"
	echo "setup - install all needed prerequisites for build"
	echo "build_image_evb - build image for EVB"
	echo "build_image_pcb - build image for PCB"
	echo "build_image_qemu - build image for QEMU"
	echo "rebuild_image_evb - rebuild image for EVB"
	echo "rebuild_image_pcb - rebuild image for PCB"
	echo "flash_to_emmc - flash image to emmc"
	echo "build_sdk - build SDK"
	echo "sync_project - syncs project sources"
}


if [ -n "$*" ]; then
	eval "$*" # execute arguments
	#echo $* finished, ret=$?
else
	if [ "$0" != "$BASH_SOURCE" ]; then
		echo $BASH_SOURCE functions are loaded into the shell environment
	else
		echo $BASH_SOURCE - a library of shell utility functions
		echo To get help run \"$BASH_SOURCE _help\"
	fi
fi

